node(null) {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        }
        junit 'test-reports/results.xml'
    }

    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk melanjutkan)'
    }

    stage('Load Environment') {
        sh """
            echo "EC2 Host: ${env.EC2_HOST}"
            echo "EC2 User: ${env.EC2_USER}"
        """
    }

    stage('Tes SSH Connection') {
        sshagent(credentials: ['ec2-ssh-key']) {
            sh """
                ssh -o StrictHostKeyChecking=no \
                    ${env.EC2_USER}@${env.EC2_HOST} \
                    'whoami && uname -a && pwd'
            """
        }
    }

    // stage('Deploy') {
    //     sshagent(credentials: ['ec2-ssh-key']) {
    //         sh """
    //             ssh -o StrictHostKeyChecking=no \
    //                 ${env.EC2_USER}@${env.EC2_HOST} \
    //                 ${DOCKER_COMMAND} \
    //         """
    //     }
    // }

    docker.image('cdrx/pyinstaller-linux:python2').inside('-u root') {
        sh 'pyinstaller --onefile sources/add2vals.py'
        sh 'cd dist'
        sh 'ls -la'
        
        // // Tahap deploy menggunakan SSH ke EC2
        // sshagent(credentials: ['ec2-ssh-key']) {
        //     sh """
        //         # Copy artifact ke server EC2
        //         scp -o StrictHostKeyChecking=no dist/add2vals ${env.EC2_USER}@${env.EC2_HOST}:/home/ubuntu/
                
        //         # Koneksi ke server dan jalankan deploy
        //         ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-ip << EOF
        //             # Stop service jika sudah ada (opsional)
        //             # sudo systemctl stop your-service || true
                    
        //             # Pindahkan binary ke lokasi yang sesuai
        //             sudo mv /home/ec2-user/add2vals /usr/local/bin/
                    
        //             # Set permission executable
        //             sudo chmod +x /usr/local/bin/add2vals
                    
        //             # Mulai service atau jalankan binary (sesuaikan dengan kebutuhan)
        //             # sudo systemctl start your-service || true
        //         EOF
        //     """
        // }
    }
}