node(null) {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        }
        junit 'test-reports/results.xml'
    }

    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk melanjutkan)'
    }

    stage('Load Environment') {
        sh """
            echo "EC2 Host: ${env.EC2_HOST}"
            echo "EC2 User: ${env.EC2_USER}"
        """
    }

    stage('Tes SSH Connection') {
        sshagent(credentials: ['ec2-ssh-key']) {
            sh """
                ssh -o StrictHostKeyChecking=no \
                    ${env.EC2_USER}@${env.EC2_HOST} \
                    'whoami && uname -a && pwd'
            """
        }
    }

    stage('Deploy') {
    //     sshagent(credentials: ['ec2-ssh-key']) {
    //         sh """
    //             ssh -o StrictHostKeyChecking=no \
    //                 ${env.EC2_USER}@${env.EC2_HOST} \
    //                 ${DOCKER_COMMAND} \
    //         """
    //     }

        docker.image('python:3.9').inside('-u root') {
            sh 'pip install pyinstaller'
            sh 'pyinstaller --onefile sources/add2vals.py'
            sh 'cd dist'
            sh 'ls -la'
            sleep time: 1, unit: 'MINUTES'
            echo 'Pipeline has finished successfully.'

            // Tahap deploy menggunakan SSH ke EC2
            withCredentials([sshUserPrivateKey(credentialsId: 'ec2-ssh-key', keyFileVariable: 'SSH_KEY')]) {
                sh """
                    mkdir /home/ubuntu/python-app
                    rm -rf mkdir /home/ubuntu/python-app/*

                    chmod 400 ${SSH_KEY}

                    scp -i ${SSH_KEY} -o StrictHostKeyChecking=no dist/add2vals ${env.EC2_USER}@${env.EC2_HOST}:/home/ubuntu/python-app
                """
            }
        }
    }
}